{% set name = "phonenumbers" %}
{% set version = "8.13.55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57c989dda3eabab1b5a9e3d24438a39ebd032fa0172bf68bfd90ab70b3d5e08b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  # license_file: No LICENSE in MANIFEST, local copy below
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Python version of Google's common library for parsing, formatting, storing and validating international phone numbers.
  dev_url: https://github.com/daviddrysdale/python-phonenumbers

extra:
  recipe-maintainers:
    - jan-janssen
