{% set name = "phonenumbers" %}
{% set version = "8.10.18" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7da5a432fbe478ca513fe2725349f796b91adbf43efa6a6e67970ff07ce6b2cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  # license_file: No LICENSE in MANIFEST, local copy below
  license_file: '{{ RECIPE_DIR }}/LICENSE'
  license: Apache 2.0
  license_family: Apache
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  dev_url: https://github.com/daviddrysdale/python-phonenumbers

extra:
  recipe-maintainers:
    - pmlandwehr
