{% set name = "phonenumbers" %}
{% set version = "8.13.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b360c756252805d44b447b5bca6d250cf6bd6c69b6f0f4258f3bfe5ab81bef69

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  # license_file: No LICENSE in MANIFEST, local copy below
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Python version of Google's common library for parsing, formatting, storing and validating international phone numbers.
  dev_url: https://github.com/daviddrysdale/python-phonenumbers

extra:
  recipe-maintainers:
    - jan-janssen
