travis:
  secure:
    BINSTAR_TOKEN: zp6K1K1HV1kfqKxO37PsU1mrKtK5UTjOYF4ymLwugGQBYrvxi8iH5qgRFbaaRR7wpaZgAR6S48jyW/VN52BhckZ9Nw95Ei/HVsPd2hLcdjhjIgUbdrusXiLfsNvZqecySyPqmtVgvW/SMr1i4uz7xwol57WlWvbZ0MAI/ieb6A9siv6hbyPMyVbosjAX9F2WMnVMw19uH8PrL9TqpzYn1TtzO7o8DGg00Asr4+VYjhLFLwJdw3UmOvTH65fcrwmxhptpHdSed+ZcTsO01opZ6GxCJWa+4bn5OokUYFCu8B4iKmOVxEVFfwFQDKLPkCVpfoCJuszhR5nbfEK444NgjxgWtqlAaHlWZ82zPGtS+pfRlkyzy+1olP8sCJiLxoUEsqq3Sm+Ep9igreLJvdBM55wYg3YFdl4ZQ5v2ej38WhL9j1nbXtp7n2CvLZeiDyZC8/uA4wcuq+hUhucPnoMJfpPXJI4aKlJfD2/K4cqOydMu2btLFkcX141KFSxoElbx3dFmgOsNPI/ApTlVesIYtvgvpxTKfQzoVOVcHhoEk5NLnstBxi46HLVj7UNK/z1po3//Qrpg5KVnWFH5fwiOtnjNRx2T7f01TlTY1203kkh+F1YGeIXbOda33u1zQDYNWW6BP/0NzwqreI8j/7lOXPpCJT1dCymJPGBpSy99e9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
